CC = gcc
CFLAGS = -Wall -Wextra -Werror
TARGET = libft.a
OBJS = main.o ft_putchar.o ft_swap.o ft_putstr.o ft_strlen.o ft_strcmp.o

INC_DIR = includes
INC = ft.h
SRC_DIR = srcs
SRCS = ft_putchar.c ft_swap.c ft_putstr.c ft_strlen.c ft_strcmp.c

all : $(TARGET)

clean:
	rm -f *.o

fclean: clean all

re: fclean all